### ISSUE TITLE
Build and Watch Tasks Don't Handle Multi-Word Folder Names

### ISSUE THREAD

**Issue by AndrewWeinmann** [kevinlyles/euchre#4]
Running the tsc:watch or tsc:build tasks when the Euchre repository is stored in a path with a multi-word folder fails.  See the error below.

> Executing task: m:\Dev Projects\Euchre\node_modules\.bin\tsc.cmd --watch -p "m:\Dev Projects\Euchre\EuchreSolution\Euchre\tsconfig.json" <
> 
> m:\Dev : The term 'm:\Dev' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + m:\Dev Projects\Euchre\node_modules\.bin\tsc.cmd --watch -p m:\Dev Pr ...
> + ~~~~~~
>     + CategoryInfo          : ObjectNotFound: (m:\Dev:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
> 
> The terminal process terminated with exit code: 1

**Comment by kevinlyles** [comment]
This is a VS Code bug.  See Microsoft/vscode#36588.

Thankfully, it was fixed in current 2 days ago, so an upcoming version of VS Code should include the fix.

**Comment by scotNZ** [comment]
This still appears to be an issue across the task related utility including tasks created through auto detect (VSCode ver 6.3) - at least on windows. 

Somehow the parsing seems to inject multiple quotes at the front of the path and tasks fail. 

Easily replicated as above..
